name = "espidf_gnat_runtime_selftest"
description = "GNAT Runtime for ESP-IDF Selftest"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "esp32", "espidf", "runtime"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = false

[[depends-on]]
espidf_gnat_runtime = "*"

[[pins]]
espidf_gnat_runtime = { path='..' }
