name = "espidf_gnat_runtime"
description = "A0B: GNAT Runtime for ESP-IDF"
website = "https://github.com/godunko/espidf_gnat_runtime"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "esp32", "espidf", "runtime"]

auto-gpr-with=false

[configuration]
generate_ada = false
generate_c = false
generate_gpr = false

[[actions]]
type = "test"
directory = "selftest"
command = ["alr", "build"]
