name = "espidf_gnat_runtime"
description = "A0B: GNAT Runtime for ESP-IDF"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "esp32", "espidf", "runtime"]

auto-gpr-with=false
project-files = ["runtime/build_runtime.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = false

[environment]
A0B_TOOLS_SVD.set = "${CRATE_ROOT}/svd/esp32s3.svd"
A0B_TOOLS_RUNTIME_DESCRIPTION.set = "${CRATE_ROOT}/runtime-esp32s3.json"

[[actions]]
type = "pre-build"
command = ["a0b-runtime", "--bb-runtimes=../../crates/bb-runtimes/", "--no-startup"]

[[depends-on]]
a0b_tools = "*"
gnat_xtensa_esp32_elf = "^15"
xtensa_dynconfig = "*"

[[pins]]
a0b_tools = { path='../../crates/a0b-tools' }
xtensa_dynconfig = { path='../../crates/xtensa-dynconfig' }
