
name: ACATS
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/godunko/espidf-alire:main
    strategy:
      fail-fast: false
      matrix:
        esp32_mcu: [esp32c3, esp32s3]
    steps:
    - name: Display environment
      run: |
        alr settings --global
        . $IDF_PATH/export.sh

    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Checkout GNAT Runtime ACATS Testsuite repo
      uses: actions/checkout@v4
      with:
        repository: godunko/espidf_gnat_runtime_acats
        path: test_apps/acats
    - name: Checkout A0B Tools
      uses: actions/checkout@v4
      with:
        repository: godunko/a0b-tools
        path: crates/a0b-tools
    - name: Checkout Xtensa Dynconfig
      uses: actions/checkout@v4
      with:
        repository: godunko/xtensa-dynconfig
        path: crates/xtensa-dynconfig
    - name: Checkout `bb-runtimes` for FSF GCC 15
      uses: actions/checkout@v4
      with:
        repository: alire-project/bb-runtimes
        ref: gnat-fsf-15
        path: crates/bb-runtimes

    - name: Build Xtensa Dynconfig
      run: |
        alr -C crates/xtensa-dynconfig --non-interactive with --solve
        alr -C crates/xtensa-dynconfig build
    - name: Build A0B Tools
      run: |
        alr -C crates/a0b-tools --non-interactive with --solve
        alr -C crates/a0b-tools build
    - name: Pin Alire crates and update `bb-runtimes` path
      run: |
        cp test_apps/acats/bundle_1/${{ matrix.esp32_mcu }}/alire.toml test_apps/acats/bundle_1
        alr toolchain --select gnat_xtensa_esp32_elf
        sed -i 's/bb-runtimes=..\/..\//bb-runtimes=/' alire.toml
        sed -i '/\[\[pins\]\]/q' alire.toml
        alr pin xtensa_dynconfig --use crates/xtensa-dynconfig
        alr pin a0b_tools --use crates/a0b-tools
        cat alire.toml
        alr --non-interactive with --solve

    - name: Build and Run tests
      run: |
        . $IDF_PATH/export.sh
        cd test_apps/acats/bundle_1
        idf.py set-target ${{ matrix.esp32_mcu }}
        idf.py qemu --qemu-extra-args --no-reboot | tee log
        ../support/report.sh log

#    - name: Run tests
#      run: |
#        . $IDF_PATH/export.sh
#        cd test_apps/acats/bundle_1
#        idf.py qemu --qemu-extra-args --no-reboot | tee log
#        ../support/report.sh log

    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@v1
      with:
        report-path: 'test_apps/acats/bundle_1/*.json'
        github-report: true
        upload-artifact: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()
